name: Develop Pull Request

on:
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project and run tests
        uses: ./.github/actions/setup-project
