name: Master Push

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      PRODUCTION_URL: "cicdreact.surge.sh"
    steps:
      - name: Setup project and run tests
        uses: ./.github/actions/setup-project

      - name: Build project and deploy to production
        uses: ./.github/actions/build-and-deploy
        with:
          deploy_url: ${{ env.PRODUCTION_URL }}
